Mistake Memory Storage (     TypeError: MemoryStorage.close() missing 1 required positional     argument: 'self') was corrected as storage = MemoryStorage()